@echo off
echo 🔄 Reiniciando servidor de desenvolvimento...

echo 📍 Verificando processos na porta 5173...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :5173') do (
    echo 🚫 Matando processo %%a...
    taskkill /f /pid %%a >nul 2>&1
)

echo ⏳ Aguardando 2 segundos...
timeout /t 2 /nobreak >nul

echo 🚀 Iniciando servidor de desenvolvimento...
npm run dev

pause 